global using FluentAssertions;
global using Moq;
global using VotingSystem.Core;
global using VotingSystem.Core.Models;
global using VotingSystem.Core.Contracts;
global using Microsoft.AspNetCore.Mvc;
global using VotingSystem.API.Controllers;
global using VotingSystem.Application;
global using VotingSystem.Application.Contracts;